CREATE TABLE account (
id INTEGER PRIMARY KEY AUTOINCREMENT,
description VARCHAR(40) UNIQUE NOT NULL,
balance DOUBLE DEFAULT 0);
CREATE TABLE cheque(
acc_id INTEGER references account(id),
prt_id INTEGER references party(id),
description CHAR,
date INTEGER,
amount DOUBLE NOT NULL,
flag CHAR);
CREATE TABLE inventory (
id VARCHAR(40),
lcn_id INTEGER NOT NULL REFERENCES location(id),
itm_id INTEGER NOT NULL REFERENCES item(id),
quantity INTEGER DEFAULT 0,
primary key(id, lcn_id, itm_id));
CREATE TABLE item (
id INTEGER PRIMARY KEY AUTOINCREMENT,
description VARCHAR(40) UNIQUE NOT NULL,
cost DOUBLE DEFAULT 0 CHECK(cost >= 0),
price DOUBLE DEFAULT 0 CHECK(price >= 0),
tax DOUBLE DEFAULT 0 CHECK(tax >= 0),
hsn CHAR(8));
CREATE TABLE location (
id INTEGER PRIMARY KEY AUTOINCREMENT,
description VARCHAR(40) UNIQUE NOT NULL,
address VARCHAR(80),
dummy BOOL DEFAULT false,
lst_sid INTEGER DEFAULT 0,
lst_pid INTEGER DEFAULT 0,
lst_tid INTEGER DEFAULT 0,
lst_aid INTEGER DEFAULT 0);
CREATE TABLE party (
id INTEGER PRIMARY KEY AUTOINCREMENT,
description VARCHAR(40) UNIQUE NOT NULL,
address VARCHAR(80),
gstn CHAR(15),
balance DOUBLE DEFAULT 0,
chq_amt DOUBLE DEFAULT 0);
CREATE TABLE pmttran (
type CHAR NOT NULL,
date INTEGER NOT NULL,
prt_id INTEGER  DEFAULT NULL REFERENCES party(id),
txn_id INTEGER  DEFAULT NULL,
acc_id INTEGER  DEFAULT NULL REFERENCES account(id),
amount DOUBLE NOT NULL,
comment VARCHAR(40),
usr_id VARCHAR(40) REFERENCES user(id),
flag CHAR);
CREATE TABLE stktran (
id INTEGER NOT NULL,
type CHAR NOT NULL,
date INTEGER NOT NULL,
lcn_id INTEGER  NOT NULL REFERENCES location(id),
prt_id INTEGER  DEFAULT NULL REFERENCES party(id),
itm_id INTEGER  NOT NULL REFERENCES item(id),
quantity INTEGER NOT NULL CHECK(quantity <> 0),
rate DOUBLE DEFAULT 0,
value DOUBLE DEFAULT 0,
tax DOUBLE DEFAULT 0,
cost DOUBLE DEFAULT 0,
usr_id VARCHAR(10) REFERENCES user(id),
invoice CHAR,
flag CHAR);
CREATE TABLE stock (
lcn_id INTEGER  NOT NULL REFERENCES location(id),
itm_id INTEGER  NOT NULL REFERENCES item(id),
quantity INTEGER DEFAULT 0,
qty_sold INTEGER DEFAULT 0,
qty_recd INTEGER DEFAULT 0,
qty_tsfr INTEGER DEFAULT 0,
qty_adjt INTEGER DEFAULT 0,
primary key(lcn_id, itm_id));
CREATE TABLE user (
id VARCHAR(40) PRIMARY KEY,
password VARCHAR(40),
description VARCHAR(40) UNIQUE NOT NULL,
access INTEGER DEFAULT 0);
